// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjUyn9m3NuBz-9ZuXsMZdaOWjqOaIf_g',
    appId: '1:359571859296:web:c78caaceeba43c33f42005',
    messagingSenderId: '359571859296',
    projectId: 'minimalshop-8f30b',
    authDomain: 'minimalshop-8f30b.firebaseapp.com',
    storageBucket: 'minimalshop-8f30b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5JmSPtmdFdvgg6xKyjPBrOmJFXKeK770',
    appId: '1:359571859296:android:de5fc198bb7a1e22f42005',
    messagingSenderId: '359571859296',
    projectId: 'minimalshop-8f30b',
    storageBucket: 'minimalshop-8f30b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmqpT8MHTcmx8lXcsYZLAXoxmwC1Lysf8',
    appId: '1:359571859296:ios:ef400c2cb7546ca9f42005',
    messagingSenderId: '359571859296',
    projectId: 'minimalshop-8f30b',
    storageBucket: 'minimalshop-8f30b.appspot.com',
    iosBundleId: 'com.example.minimalEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmqpT8MHTcmx8lXcsYZLAXoxmwC1Lysf8',
    appId: '1:359571859296:ios:f76091df4b9f8b56f42005',
    messagingSenderId: '359571859296',
    projectId: 'minimalshop-8f30b',
    storageBucket: 'minimalshop-8f30b.appspot.com',
    iosBundleId: 'com.example.minimalEcommerceApp.RunnerTests',
  );
}
